### ISSUE TITLE
Error about converting .sam to .bam after BlastToSam

### ISSUE THREAD

**Issue by claczny** [AstrorEnales/BlastToSam#2]
Hi,

I get the following error message from SAMtools-0.1.19 with the most recent version of BlastToSam when applying it to an NCBI-BLAST+-2.2.30-based alignment of two reconstructed bacterial genomes, i.e., both represented by multiple contigs. 
Unfortunately, I can not share the files but the command lines used:

```
blastn -num_threads 12 -query query.fa -db ./target -outfmt 11 -out ./query-blastn_against-target.asn
blast_formatter -archive ./query-blastn_against-target.asn -out ./query-blastn_against-target.out -outfmt 0
java -jar BlastToSam.jar -i query-blastn_against-target.out -o query-blastn_against-target.out.sam
samtools view -bS query-blastn_against-target.out.sam > query-blastn_against-target.out.bam
```

Do you have any idea what might be the problem?

```
[samopen] SAM header is present: 29 sequences.
Line 129, sequence length 129 vs 117 from CIGAR
Parse error at line 129: CIGAR and sequence length are inconsistent
Aborted
```

Thank you very much for your support.

Best,

Cedric

UPDATE:
I tried SAMtools-1.2 which returns the following

```
[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] parse error at line 129
[main_samview] truncated file.
```

**Comment by AstrorEnales** [comment]
Hey, sorry you ran into this bug. PicardTool didn't throw errors which i used to check the results. Now i'm checking with samtools too in the future.
Bug should be fixed and the download is updated :)

**Comment by claczny** [comment]
Great! Thanks for the quick fix! It works like a charm now for aligning a query assembly against a target assembly.

**Comment by AstrorEnales** [comment]
Wonderfull to hear :) and thanks for sticking with the tool!
